CLEANING_CONFIGS = {
    "bfrss_computed_vars": [
        "DRNKANY6",
        "DROCDY4_",
        "_AGE65YR",
        "_AGE80",
        "_AGEG5YR",
        "_AGE_G",
        "_ASTHMS1",
        "_CASTHM1",
        "_CHLDCNT",
        "_CURECI3",
        "_DENVST3",
        "_DRNKWK3",
        "_EDUCAG",
        "_EXTETH3",
        "_HCVU654",
        "_HLTHPL2",
        "_INCOMG1",
        "_LCSAGE",
        "_LTASTH1",
        "_MENT14D",
        "_PHYS14D",
        "_RFBING6",
        "_RFBMI5",
        "_RFDRHV9",
        "_RFHLTH",
        "_RFSMOK3",
        "_SEX",
        "_SMOKER3",
        "_TOTINDA",
    ],
    "bfrss_chronic_health_conditions_vars": ["DIABETE4"],
    "bfrss_health_care_access_vars": ["CHECKUP1", "MEDCOST1", "PERSDOC3", "PRIMINS2"],
    "bfrss_health_status_vars": ["GENHLTH"],
    "bfrss_healthy_days_vars": ["MENTHLTH", "PHYSHLTH"],
    "bfrss_oral_health_vars": ["LASTDEN4", "RMVTETH4"],
    "bfrss_record_identification_vars": ["DISPCODE", "_STATE"],
}
