SURVEYS_DATA_TYPES = {
    "is_your_blood_pressure_high": "int32",
    "is_your_cholesterol_high": "int32",
    "have_you_had_a_cholesterol_check_in_last_5years": "int32",
    "your_bmi_value": "float32",
    "have_you_ever_smoked_at_least_100cigs": "int32",
    "have_you_ever_had_stroke": "int32",
    "have_you_ever_had_coronary_heart_disease_or_myocardial_infarction": "int32",
    "did_you_exercise_in_last_30days": "int32",
    "do_you_eat_fruits_daily": "int32",
    "do_you_eat_veggies_daily": "int32",
    "are_you_a_man_with_at_least_14drinks_per_week_or_a_woman_with_at_least_7drinks_per_week": "int32",
    "are_you_covered_by_any_healthcare_insurance": "int32",
    "was_there_a_time_in_last_12months_you_could_not_afford_a_doctor_because_of_cost": "int32",
    "your_health_level_in_general": "int32",
    "how_many_days_during_last_30days_your_mental_health_was_bad": "int32",
    "how_many_days_during_last_30days_your_physical_health_was_bad": "int32",
    "have_you_serious_walking_difficulty": "int32",
    "your_gender": "int32",
    "your_age": "int32",
    "your_education_level": "int32",
    "your_income_level": "int32",
    "have_you_diabetes_or_prediabetes": "int32",
}
